config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents, only: [:index, :new, :create, :show, :edit, :update, :destroy ]

  resources :procedure_requests, only: [:index, :update, :show, :destroy]


  namespace :pro do
    resources :procedure_requests do
      get "download_zip", to: "pro_procedures", as: "download_zip"
    end
  end

  get "/download/:id", to: "documents#download", as: "download"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="reseaux-sociaux">
    <ul class="list-inline">
      <li>
        <a href=""><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
      </li>
      <li>
        <a href=""><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
      </li>
      <li>
        <a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a>
      </li>
    </ul>
  </div>
  <div class="pages">
    <ul class="list-inline">
      <li>
        <a href="#">Mentions légales</a>
      </li>
      <li>
        <a href="#">Contact</a>
      </li>
      <li>
        <a href="#">FAQ</a>
      </li>
    </ul>
  </div>
  <div class="copyright">
    <p>&copy;FileOn 2017</p>
  </div>
</div>

app/views/shared/_nav_btn.html.erb
<div class="op">
  <div class="button-upload">
    <%= link_to "Upload", new_document_path, class: "btn btn-success", id: "btn-upload" %>
    <% if current_user && current_user.part? && current_user.has_new_procedure_request? %>
      <%= link_to procedure_requests_path, class: "btn-fileon-alert" do %>
        <div class="btn btn-warning">Alerte</div>
        <div class="alert-pin"><%= current_user.part_procedures.pending.count %></div>
      <% end %>
      <%#= link_to "Vous avez reçu une nouvelle demande", procedure_requests_path, class: "btn btn-warning" %>
    <% end %>
  </div>
  <div class="form-inline" id="the-basics">
   <%= simple_form_for :search, url: documents_path, :method => :get do |f| %>
    <%= f.input :tag , input_html: { class: "typeahead" }, placeholder: "Passeport", label: false %>
  <%= f.submit 'Search', class:"btn btn-primary", id: 'search-btn'%>
  <% end %>
  </div>
</div>

<% content_for(:after_js) do %>

<script>
  var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
      var matches, substringRegex;

      // an array that will be populated with substring matches
      matches = [];

      // regex used to determine if a string contains the substring `q`
      substrRegex = new RegExp(q, 'i');

      // iterate through the pool of strings and for any string that
      // contains the substring `q`, add it to the `matches` array
      $.each(strs, function(i, str) {
        if (substrRegex.test(str)) {
          matches.push(str);
        }
      });

      cb(matches);
    };
  };


  var states = [ "Carte d'identité", "Passeport", "Permis de conduire", "Carte grise",
  "RIB", "Relevé bancaire", "Bulletin de salaire", "Contrat de travail", "Carte vital", "Carnet de santé", "Justificatif de domicile", "Quittance de loyer", "Certificat de scolarité", "Diplomes"
  ];

  $('#the-basics .typeahead').typeahead({
    hint: true,
    highlight: true,
    minLength: 1
  },
  {
    name: 'states',
    source: substringMatcher(states)
  });
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Contact", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://avatars0.githubusercontent.com/u/29281750?v=4&s=460", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_side_nav.html.erb
<div class="side hidden-xs">
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "Fileon.png" ,class:"logo" %>
  <% end %>
  <div class="bottom">
    <p class=" <%= 'selected' if @selected ==  'Upload'%> "> <%= link_to 'Upload', new_document_path %> </p>
    <p class=" <%= 'selected' if @selected == 'Documents' %> "> <%= link_to 'Documents', documents_path %> </p>
    <p class=" <%= 'selected' if @selected == 'Procédures' %> ">
     <%= link_to 'Procédures', default_procedure_requests_past(current_user) %>
    </p>
  </div>
</div>