config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents, only: [:index, :new, :create, :show, :edit, :update, :destroy ]

  resources :procedure_requests, only: [:index, :update, :show, :destroy]


  namespace :pro do
    resources :procedure_requests do
      get "download_zip", to: "pro_procedures", as: "download_zip"
    end
  end

  get "/download/:id", to: "documents#download", as: "download"

end

app/models/procedure_request.rb
class ProcedureRequest < ApplicationRecord
  enum status: { pending: 0, validated: 1 }

  # belongs_to :user
  belongs_to :procedure
  has_many :requested_tags, through: :procedure
  has_many :tags, through: :requested_tags

  # belongs_to :pro, class_name: :User, foreign_key: :pro_id
  belongs_to :pro, class_name: "User"
  belongs_to :part, class_name: "User"

  validates :pro , presence: true
  validates :part , presence: true
  validates :procedure , presence: true

  def valid_for?(user)
    # bool = true
    # tags.each { |tag| bool = bool && tag.complete_for?(user) }
    # bool

    # complete = tags.reduce(true) { |bool, tag| bool = bool && tag.complete_for?(user) && !tag.expired_for?(user) }

    # status = []
    # self.tags.each do |tag|
    #   status << tag.expired_for?(user)
    # end
    # expired = status.include? true

    # return complete && !expired
    tags.reduce(true) { |bool, tag| bool = bool && tag.complete_for?(user) && !tag.expired_for?(user) }
  end

  def progression(user) # number of tags upload in the category
    progress = 0
    tags.each do |tag|
      if tag.complete_for?(user)
        progress += 1
      end
    end
    "#{progress} / #{tags.size}"
  end

  def procedure_documents
    # self.part.documents.where(tag: self.tags)
    part.documents.where(tag: tags)
  end

end

app/controllers/pro/procedure_requests_controller.rb
class Pro::ProcedureRequestsController < ApplicationController
  def index
    @procedure_requests = current_user.pro_procedures.all
    @selected = "Procédures"
  end

  def show
    @procedure_request = ProcedureRequest.find(params[:id])
  end

  def new
    @procedure_request = current_user.pro_procedures.new
    # @procedures = Procedure.all
  end

  def create
    @part = User.find_by_email(procedures_params[:email])
    @pro = current_user
    @procedure_request = ProcedureRequest.new(pro: @pro, part: @part, procedure_id: procedures_params[:procedure_id])
    @procedure_request.status = "pending"
    if @procedure_request.save

      redirect_to pro_procedure_requests_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def download_zip

    @procedure_request = ProcedureRequest.find(params[:procedure_request_id])

    part = @procedure_request.part
    part_fullname = "#{part.first_name} #{part.last_name}"

    #récupérer les documents requis de la procedure en cours
    documents = @procedure_request.procedure_documents
    public_ids = []
    documents.each do |document|
      public_ids += document.photos.map(&:public_id)
    end
    redirect_to Cloudinary::Utils.download_zip_url(:public_ids => public_ids, target_public_id: part_fullname)

  end





  private

  def procedures_params
    params.require(:selection).permit(:email, :procedure_id)
  end

end

app/controllers/procedure_requests_controller.rb
class ProcedureRequestsController < ApplicationController
  def index
    @procedure_requests = current_user.part_procedures.all
    @selected = "Procédures"
  end

  def show
    @procedure_request = ProcedureRequest.find(params[:id])
  end

  def update
    procedure = ProcedureRequest.find(params[:id])
    procedure.update(procedure_request_params)
    redirect_to procedure_requests_path
  end

  def destroy
    procedure = ProcedureRequest.find(params[:id])
    procedure.destroy
    redirect_to procedure_requests_path
  end


  private

  def procedure_request_params
    params.permit(:status)
  end


end

app/views/procedure_requests/index.html.erb
<% content_for(:title_tag) do %>
  Procédures en cours .
<% end %>

<% @procedure_requests.pending.each do |procedure_request|  %>
  <h5><%= procedure_request.procedure.name %>
    envoyé par
  <%= procedure_request.pro.first_name %>
  <%= procedure_request.pro.last_name %>
  <%= procedure_request.pro.company %>
  </h5>
  <h2> <%= link_to "Accepter", procedure_request_path(procedure_request, status: :validated), method: :patch, class: "btn btn-success" %>
       <%= link_to "Refuser", procedure_request_path(procedure_request), method: :delete, class: "btn btn-danger" %>
  </h2>
 <% end %>


<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<% @procedure_requests.validated.each do |procedure_request| %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= procedure_request.id %>" aria-expanded="true" aria-controls="collapse<%= procedure_request.id %>">
          <%= procedure_request.procedure.name %>
          <% if procedure_request.valid_for?(procedure_request.part) %>
            <i class="fa fa-check presence-icon" aria-hidden="true"></i>
          <% else %>
            <i class="fa fa-exclamation-circle expiration-icon" aria-hidden="true"></i>
          <% end %>
        </a>
      </h4>
    </div>
    <div id="collapse<%= procedure_request.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
      <ul>
        <% procedure_request.procedure.tags.each do |tag| %>
          <li>
            <%= tag.name %>
            <% if tag.complete_for?(procedure_request.part) %>
              <% procedure_request.part.documents.where(tag: tag).each do |document| %>
                <% if document.expired?  %>
                  <i class="fa fa-exclamation-circle expiration-icon" data-toggle="tooltip" title="Le date d'expiration du document est arrivée à échéance" aria-hidden="true"></i>
                <% else %>
                  <i class="fa fa-check presence-icon" aria-hidden="true"></i>
                <% end %>
              <% end %>
            <% else %>
              <i class="fa fa-times" aria-hidden="true"></i>
              <%= link_to "Ajouter", new_document_path(document: { tag_id: tag.id }), class: "btn btn-primary btn-xs" %>
            <% end %>
          </li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>
<% end %>
</div>