config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :documents, only: [:index, :new, :create, :show, :edit, :update, :destroy ]

  resources :procedure_requests, only: [:index, :update, :show, :destroy]


  namespace :pro do
    resources :procedure_requests do
      get "download_zip", to: "pro_procedures", as: "download_zip"
    end
  end

  get "/download/:id", to: "documents#download", as: "download"

end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :tag

  validates :photos, presence: true
  validates :document_date, presence: true
  validates :tag, presence: true
  delegate :validity, to: :tag, allow_nil: true

  has_attachments :photos, maximum: 12#, maximum: tag.number_of_uploads


  def limit_date
    self.document_date + self.tag.validity
  end


  def expired?
    self.limit_date < Date.today
  end

  def self.valid_date(tag)
    self.where(tag: tag)
        .where("document_date > ?", (Date.today - tag.validity))
  end

  def self.unvalid_date(tag)
    self.where(tag: tag)
        .where("document_date < ?", (Date.today - tag.validity))
  end

end

app/controllers/documents_controller.rb
require "open-uri"

class DocumentsController < ApplicationController

  before_action :set_document, only: [:show, :edit, :update, :destroy]

  def index
    @documents = Document.where(user: current_user)
    @categories = Category.all
    @selected = "Documents"
  end

  def new
    @document = Document.new(tag_id: params.dig(:document, :tag_id))
    @tags = Tag.all
    @selected = "Upload"
  end

  def create
    @document = current_user.documents.build(document_params)
    if @document.valid?
      @document.save
      flash[:notice] = "Votre document a bien été ajouté à votre librairie"
      redirect_to documents_path
    else
      render :new
    end
  end


  def edit
    @tags = Tag.all
  end

  def update
     if @document.update(document_params)
      redirect_to documents_path
    else
      render :edit
    end
  end

  def destroy
    @document.destroy
    flash[:notice] = "Votre document a bien été supprimé"
    redirect_to documents_path
  end

  def download
    data = open("http://res.cloudinary.com/dlizgzwic/image/upload/#{Document.find(params[:id]).photos.first.path}")
    send_data data.read, filename: "doc.#{Document.find(params[:id]).photos.first.format}", type: "application/#{Document.find(params[:id]).photos.first.format}"
  end



  private

  def document_params
    params.require(:document).permit(:tag_id, :document_date, photos: [])
  end

  def set_document
    @document = Document.find(params[:id])
  end

end

app/views/documents/_modal.html.erb
<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal fade" id=<%="tag#{tag.id}"%> tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= tag.name %></h4>
      </div>
      <div class="modal-body">
        <div class="text-center">
           <h1> </h1>

          <div class="overview">
          <% if document.photos? %>

            <% document.photos.each do |photo| %>
                <%= cl_image_tag photo.path, crop: :fill, class: "contain" %>
            <% end %>
          <% end %>
         <!--  <p>Date du document : <%= document.document_date %></p> -->
          <p>Expire le : <%= document.document_date + document.tag.validity  %> </p>

          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Download", download_path(document), class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_document_path(document), class: "btn btn-primary" %>
        <%= link_to 'Delete', document_path(document), method: :delete , class: "btn btn-danger", data: { dismiss: "modal"}%>







      </div>
    </div>
  </div>
</div>

app/views/documents/edit.html.erb
<% content_for(:title_tag, 'FileOn - Edition du document') %>

<div class="container">
  <div class="row">
     <div class="col-xs-12 col-sm-6 col-sm-offset-3 form">
       <div class="text-center">
        <h1>Upload a document</h1>
        </div>
       <%= simple_form_for @document do |d| %>
         <%= d.input :photos, as: :attachinary %>
         <%= d.input :document_date, as: :string, label: "Date d'émission du document", input_html: {id: 'sandbox-container'} %>
         <%= d.submit class: "text-center btn btn-primary" %>
       <% end %>
     </div>
 </div>
</div>

app/views/documents/index.html.erb
 <% content_for(:title_tag) do %>
   Mes Documents sur File On
 <% end %>
 <div class="right-column">
  <div class="first-block">
    <h1>Mes documents</h1>

    <div class="panel-group first-child" id="accordion" role="tablist" aria-multiselectable="true">

      <% @categories.each do |category| %>
<!-- ============================= Acordeon Principal ============================ -->
        <div class="panel panel-default">

          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= category.id %>" aria-expanded="true" aria-controls="collapse<%= category.id %>">
            <div class="panel-heading category" role="tab" id="headingOne">

              <!-- ========================= Affichage de a categorie ====== -->
              <h4 class="panel-title text-center">
                   <span class="pull-left"> <i class="<%= category.icon %> " aria-hidden="true"></i></span><%=category.name %>


                  <% if category.valid_for?(current_user) %>

                    <i class="fa fa-check presence-icon" aria-hidden="true"></i>
                  <% else %>
                    <i class="fa fa-exclamation-circle expiration-icon" aria-hidden="true"></i>
                  <% end %>
                  <span class="pull-right"> <%= category.progression(current_user) %></span>
              </h4>

            </div>
          </a>


          <div id="collapse<%= category.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">

            <div class="panel-body">
              <div class="panel-group first-child" id="accordion<%= category.id %>" role="tablist" aria-multiselectable="true">

                <% category.tags.each do |tag| %>

                  <% if tag.number_of_uploads <= 1 %>

              <!-- ============== Si 1 seul document -->

                      <%= link_to tag.name, "#tag#{tag.id}", data: { toggle: "modal"} %>
                      <% if tag.complete_for?(current_user) %>


                        <% @documents.where(tag: tag).each do |document| %>
                          <%= render 'modal', tag: tag, document: document  %>
                          <% if document.expired? %>
                            <i class="fa fa-exclamation-circle expiration-icon" aria-hidden="true"> Date de validité dépassée</i>
                          <% else %>
                            <i class="fa fa-check presence-icon" aria-hidden="true"></i>
                          <% end %>

                        <% end %>

                      <% else %>
                        <%= link_to "Ajouter", new_document_path(document: { tag_id: tag.id }), class: "btn btn-primary btn-xs" %>
                      <% end %>
                    <br>

                  <% else %>
<!-- =============== Si + de 1 document ======================  -->

                  <!-- ============ Acordéon secondaire head -->
                    <div class="panel-group" id="accordion<%= tag.id %>" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default tag-multiple">

                      <a role="button" data-toggle="collapse" data-parent="#accordion<%= category.id %>" href="#collapse_tag<%=tag.id %>" aria-expanded="true" aria-controls="collapse_tag<%= tag.id %>">
                        <div class="panel-heading tag-multiple" role="tab" id="headingOne">
                          <h4 class="panel-title ">
                              <%= link_to tag.name, "#collapse_tag#{tag.id}", data: { toggle: "collapse", parent: "accordion#{tag.id}"} %>


                                <% if tag.complete_for?(current_user) %>

                                  <% if check_documents_in_tag_expired?(@documents, tag)%>
                                    <i class="fa fa-exclamation-circle expiration-icon" aria-hidden="true"> Date de validité dépassée</i>
                                  <% else %>
                                    <i class="fa fa-check presence-icon" aria-hidden="true"></i>
                                  <% end %>

                                <% else %>
                                  <%= link_to "Ajouter", new_document_path(document: { tag_id: tag.id }), class: "btn btn-primary btn-xs add-btn" %>
                                <% end %>
                          </h4>
                        </div>
                      </a>
                  <!-- =========== Fin du head de l'acordeon secondaire ======== -->

                      <div id="collapse_tag<%=tag.id %>" class="panel-collapse collapse tab-multiple" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body tag-multiple">

                            <% current_user.documents.where(tag: tag).each do |document| %>
                            <!-- affiche le nom du tag et sa date  -->
                              <%= link_to "#{tag.name} #{document.document_date.strftime('%m/%y')}", "#tag#{tag.id}", data: { toggle: "modal"} %>

                              <%= render 'modal', tag: tag, document: document  %>
                                <% if document %>


                                    <% if document.expired? %>
                                      <i class="fa fa-exclamation-circle expiration-icon" aria-hidden="true"> Date de validité dépassée</i>
                                    <% else %>
                                      <i class="fa fa-check presence-icon" aria-hidden="true"></i>
                                    <% end %>



                                <% else %>
                                  <%= link_to "Ajouter", new_document_path(document: { tag_id: tag.id }), class: "btn btn-primary btn-xs" %>
                                <% end %>


                              <br>
                            <% end %>



                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/documents/new.html.erb
<% content_for(:title_tag) do %>
  Télécharger un nouveau document
<% end %>
<div class="right-column">
  <div class="first-block">
    <div class="text-center">
    <h2>Télécharger des documents</h2>
    </div>
    <div class="form-for">
      <%= simple_form_for @document do |d| %>
       <label class="text-center fileUpload">
          <span class="upload btn btn-primary">Sélectionner</span>
          <%= d.input :photos, as: :attachinary, label: false, class: "upload" %>
       </label>
       <%= d.input :document_date, as: :string, label: "Date d'émission du document", input_html: {id: 'sandbox-container'} %>
       <%= d.association :tag, prompt: "Type de Document", as: (:hidden if @document.tag) %>
       <%= d.submit class: "btn btn-primary" %>
     <% end %>
    </div>
  </div>
</div>